name: Deploy Laravel Portfolio to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # --- IMPORTANT FIX 1: Add the environment declaration here for Pages deployment ---
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # Optional: displays the deployed URL in the Actions UI

    # --- IMPORTANT FIX 2: Move permissions to the job level ---
    # Grant GITHUB_TOKEN the permissions required for Pages deployment
    permissions:
      contents: read # Required to checkout the code
      pages: write # Grants the GITHUB_TOKEN write permission to deploy to GitHub Pages
      id-token: write # Required for OIDC support (used by actions/deploy-pages)
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build static site
        run: npm run build
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # --- IMPORTANT FIX 3: Correct the path to your actual build output directory ---
          # It should be './dist/public' if your index.html is inside the public folder.
          path: './dist/public' 
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4